version: '3.6'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    restart: unless-stopped

  redis:
    image: redis:5-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY}
      MINIO_SECRET_KEY: ${AWS_SECRET_KEY} 
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:
