version: '3'

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:4-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data
  app:
    build:
      context: .
    environment:
      RAILS_ENV: production
      RAILS_FORCE_SSL: 1
      PORT: 3000
      DB_HOST: postgres
      DB_NAME: app
      REDIS_URL: redis://redis:6379
    ports:
      - "3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      APP_NAME: app
      APP_DOMAIN: app.local
      APP_PATH: /app
      APP_PORT: 3000
      CERT_PATH: /app/docker-configs/certs/nginx-selfsigned.crt
      CERT_KEY_PATH: /app/docker-configs/certs/nginx-selfsigned.key
      DH_PARAM_PATH: /app/docker-configs/certs/dhparam-2048.pem
    ports:
      - 80:80
      - 443:443
    links:
      - app
    depends_on:
      - app
    volumes:
      - app_data:/app/public
  worker:
    build:
      context: .
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_NAME: app
      REDIS_URL: redis://redis:6379
    links:
      - postgres
      - redis
    depends_on:
      - app
volumes:
  app_data:
  postgres_data:
  redis_data:
