version: '3.6'

services:
  app:
    build:
      context: .
    environment:
      RAILS_ENV: development
      PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      REDIS_URL: ${REDIS_URL}
    ports:
      - ${APP_PORT}
      - "3035"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      APP_NAME: ${APP_NAME}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_PATH: ${APP_PATH}
      APP_PORT: ${APP_PORT}
      APP_ENV: development
      CERT_PATH: /app/docker-configs/certs/nginx-selfsigned.crt
      CERT_KEY_PATH: /app/docker-configs/certs/nginx-selfsigned.key
      DH_PARAM_PATH: /app/docker-configs/certs/dhparam-2048.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./public:/app/public
    restart: unless-stopped

  worker:
    build:
      context: .
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
      PORT: 3001
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - app
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
