default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] || 'app' %>_development

test:
  <<: *default
  database: <%= ENV["DB_NAME"] || 'app' %>_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] || 'app' %>_production
